# Generated by Django 3.0.7 on 2021-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noticeboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_notice', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
