# Generated by Django 3.0.7 on 2021-03-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('tender_link', models.URLField()),
                ('tender_name', models.TextField()),
                ('contact', models.TextField()),
                ('dept', models.TextField()),
            ],
        ),
    ]
