# Generated by Django 3.0.7 on 2021-03-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_tender'),
    ]

    operations = [
        migrations.CreateModel(
            name='acadcalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='scedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField()),
                ('desc', models.TextField()),
                ('date', models.DateTimeField()),
                ('link', models.URLField()),
            ],
        ),
    ]
