# Generated by Django 3.0.7 on 2021-03-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.TextField()),
                ('post', models.TextField()),
                ('vacancy', models.IntegerField()),
                ('last_date', models.DateTimeField()),
                ('link', models.URLField()),
            ],
        ),
    ]
