# Generated by Django 3.0.7 on 2021-03-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='careerDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.TextField()),
                ('post', models.TextField()),
                ('vacancy', models.IntegerField()),
                ('last_date', models.DateTimeField()),
                ('specialization', models.TextField()),
                ('qualification', models.TextField()),
                ('appl_link', models.URLField()),
                ('full_notification_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='career',
        ),
    ]
