# Generated by Django 3.0.7 on 2021-03-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_upcomingevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='upcomingeventss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('event_name', models.CharField(max_length=50)),
                ('venue', models.TextField()),
                ('contact', models.TextField()),
                ('doc', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='upcomingevents',
        ),
    ]
